### ISSUE TITLE
The paper used  the label of center 750ms as label of the whole 1.5s segment, but it seems that in your code you use the whole 1.5s segment to calculate the label.

### ISSUE THREAD

**Issue by wenyuqing** [cvqluu/nn-similarity-diarization#5]
def segment_labels(segments, rttm, xvectorscp, xvecbase_path=None):
    segment_cols = load_n_col(segments, numpy=True)
    segment_rows = np.array(list(zip(*segment_cols))) #解压
    rttm_cols = load_n_col(rttm, numpy=True)
    vec_utts, vec_paths = load_n_col(xvectorscp, numpy=True)
    if not xvecbase_path:
        xvecbase_path = os.path.dirname(xvectorscp)
    assert sum(vec_utts == segment_cols[0]) == len(segment_cols[0])
    vec_paths = change_base_paths(vec_paths, new_base_path=xvecbase_path)

    rttm_cols.append(rttm_cols[3].astype(float) + rttm_cols[4].astype(float))#起始时间+duration=结束时间
    recording_ids = sorted(set(segment_cols[1])) # recording_id 如iaaa
    events0 = np.array(segment_cols[2:4]).astype(float).transpose() #segment起止时间
    events1 = np.vstack([rttm_cols[3].astype(float), rttm_cols[-1]]).transpose() #ref起止时间（groundtruth)

    rec_batches = []

    for rec_id in tqdm(recording_ids): #tqdm是进度条
        seg_indexes = segment_cols[1] == rec_id  #recording_id iaaa ==优先级高
        rttm_indexes = rttm_cols[1] == rec_id
        ev0 = events0[seg_indexes]   #rec_id对应的segment里每段的起止时间
        ev1 = events1[rttm_indexes]  #rec_id对应的rffm里每段音频的起止时间
        ev1_labels = rttm_cols[7][rttm_indexes] #rec_id对应的rffm里每段音频的speaker
        ev0_labels = assign_overlaps(evnew, ev1, ev1_labels)
        ev0_labels = ['{}_{}'.format(rec_id, l) for l in ev0_labels]  #形成speaker_id,如iaaa_A
        batch = (segment_cols[0][seg_indexes], ev0_labels, vec_paths[seg_indexes], segment_rows[seg_indexes])
        rec_batches.append(batch)

    return recording_ids, rec_batches

**Comment by cvqluu** [comment]
I think what assign_overlaps does is assign a label based on the labelled segment with the most overlap with the unlabelled segment.

(It has been a while since I've touched the bulk of this code, so I could well be wrong!)

Feel free to change this in your own implementation should you desire, I'm not really actively maintaining this repo - hopefully it still has some useful bits and pieces for you to use.

**Comment by cvqluu** [comment]
Or if you feel up to it, submit a pull request that modifies this part, or provides the option.

**Comment by wenyuqing** [comment]
Thanks for your patient reply! I am a beginner in this area and I need to check this issue more carefully

**Comment by cvqluu** [comment]
In which case I'll close the issue for now :)
